Expecting ':' delimiter: line 1 column 9 (char 8)Traceback (most recent call last):
  File "F:\Charles_Files\Personal Projects\Personal Games\dependencies\custom-documentation-generator\driver.py", line 88, in <module>
    create_output()
  File "F:\Charles_Files\Personal Projects\Personal Games\dependencies\custom-documentation-generator\driver.py", line 57, in create_output
    comment_list = util_functions.produce_comments(data)
  File "F:\Charles_Files\Personal Projects\Personal Games\dependencies\custom-documentation-generator\util_functions.py", line 44, in produce_comments
    return json.loads(response.choices[0].message.content)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 9 (char 8)
